refactor: use common deploy workflow

diff --git a/.github/workflows/deployment.yaml b/.github/workflows/deployment.yaml
--- a/.github/workflows/deployment.yaml
+++ b/.github/workflows/deployment.yaml
@@ -1,7 +1,7 @@
 name: Interop Analytics Deployment
 run-name: "${{ github.ref_name }} / ${{ inputs.environment }} - Interop Analytics Deployment"
 
-on: 
+on:
   workflow_dispatch:
     inputs:
       environment:
@@ -28,12 +28,6 @@ on:
         required: true
         default: true
         type: boolean
-      apply_mv:
-        description: 'Run Flyway migrations for applying materialized views on Redshift'
-        required: true
-        default: false
-        type: boolean
-
 
 permissions:
   id-token: write
@@ -54,17 +48,18 @@ jobs:
           echo "- run_k8s_workflow: \`${{ inputs.run_k8s_workflow }}\`" >> $GITHUB_STEP_SUMMARY
           echo "- run_tf_apply_monitoring_workflow: \`${{ inputs.run_tf_apply_monitoring_workflow }}\`" >> $GITHUB_STEP_SUMMARY
           echo "- run_tf_apply_secrets_workflow: \`${{ inputs.run_tf_apply_secrets_workflow }}\`" >> $GITHUB_STEP_SUMMARY
-          echo "- apply_mv: \`${{ inputs.apply_mv }}\`" >> $GITHUB_STEP_SUMMARY
           echo "- HELM_FORCE_UPGRADE_MICROSERVICES_CSV: \`${{ vars.HELM_FORCE_UPGRADE_MICROSERVICES_CSV }}\`" >> $GITHUB_STEP_SUMMARY
           echo "- HELM_FORCE_UPGRADE_CRONJOBS_CSV: \`${{ vars.HELM_FORCE_UPGRADE_CRONJOBS_CSV }}\`" >> $GITHUB_STEP_SUMMARY
 
   initChecks:
     runs-on: ubuntu-22.04
     environment: ${{ inputs.environment }}
+    outputs:
+      infra_commons_tag_computed: ${{ steps.extract-deploy-wf-tag.outputs.infra_commons_tag_computed }}
     steps:
       - name: Check user is a ${{ vars.ALLOWED_DEPLOY_GH_TEAMS }} team member
         id: checkUserPermissions
-        if: ${{ inputs.environment != 'dev-analytics' }}
+        if: ${{ inputs.environment != 'dev' }}
         env:
             GITHUB_TOKEN: ${{ secrets.BOT_TEAMS_RO_PAT }}
             ORG: ${{ github.repository_owner }}
@@ -78,11 +73,11 @@ jobs:
 
           for TEAM in $TEAMS_LIST; do
             set +e
-            # Check current user membership with gh api 
-            echo "Check if user is member of $TEAM"           
+            # Check current user membership with gh api
+            echo "Check if user is member of $TEAM"
             GH_TEAM_MEMBERSHIP_RESPONSE=$(gh api -i --method GET -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" \/orgs/$ORG/teams/$TEAM/memberships/$USER)
             set -e
-            
+
             # Extract the HTTP status code
             HTTP_CODE=$(echo $GH_TEAM_MEMBERSHIP_RESPONSE | head -n 1 | cut -d' ' -f 2)
 
@@ -94,13 +89,52 @@ jobs:
               echo "User is NOT member of $TEAM"
             fi
           done
-            
+
           if [[ $CHECK_SUCCESS -eq 0 ]]; then
             echo "::error:: Resource not found. Please check the organization ($ORG), team ($TEAMS), and username ($USER). $USER is not memeber of specified teams."
             exit 1
           fi
 
           echo "$USER has the correct permissions to execute the workflow."
+
+      - name: Checkout repo @ current ref
+        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29
+        with:
+          ref: ${{ github.ref }}
+
+      - name: Extract deployment reusable workflow used tag
+        id: extract-deploy-wf-tag
+        run: |
+          set -euo pipefail
+
+          WORKFLOW_FILE=".github/workflows/deployment.yaml"
+
+          if [[ ! -f "$WORKFLOW_FILE" ]]; then
+            echo "::error:: Workflow file '$WORKFLOW_FILE' not found."
+            exit 1
+          fi
+          job_content=$(yq e '.jobs.deploy // ""' .github/workflows/deployment.yaml)
+          if [[ -z "$job_content" ]]; then
+            echo "::error:: 'deploy' job not found in the workflow file."
+            exit 1
+          fi
+
+          fullref=$(yq e '.jobs."deploy".uses' .github/workflows/deployment.yaml)
+
+          tag=${fullref#*@}
+
+          echo "fullref=$fullref"
+          echo "tag=$tag"
+
+          if [[ -n "${{ vars.INFRA_COMMONS_TAG }}" ]]; then
+            final_tag="${{ vars.INFRA_COMMONS_TAG }}"
+          else
+            final_tag="$tag"
+          fi
+          echo "infra_commons_tag_computed=$final_tag" >> $GITHUB_OUTPUT
+
+      - name: Show extracted tag
+        run: echo "infra_commons_tag_computed = ${{ steps.extract-deploy-wf-tag.outputs.infra_commons_tag_computed }}"
 
   create_runner:
     name: Create Self-Hosted Runner
@@ -112,7 +146,7 @@ jobs:
       ecs_task_id: ${{ steps.start_runner.outputs.ecs_task_id }}
     strategy:
       matrix:
-        index: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]
+        index: [1,2,3,4,5,6,7,8,9,10]
       fail-fast: false
     steps:
       - name: Start GitHub Runner
@@ -144,24 +178,22 @@ jobs:
 # The following 'deploy' job must be executed when:
 # we want to deploy microservices and cronjobs to k8s (inputs.run_k8s_workflow is TRUE)
 # AND
-#   we don't want to apply secrets to k8s (!inputs.run_tf_apply_secrets_workflow && needs.tf_apply_secrets.result == 'skipped')		
+#   we don't want to apply secrets to k8s (!inputs.run_tf_apply_secrets_workflow && needs.tf_apply_secrets.result == 'skipped')
 #   OR
 #   we want to apply secrets to k8s (inputs.run_tf_apply_secrets_workflow && needs.tf_apply_secrets.result == 'success')
 ###
 # Note: always() is required because the following job has a dependency with 'tf_apply_secrets' job.
 # In case we don’t want to deploy secrets to k8s, the 'tf_apply_secrets' job would be skipped and the current job would be skipped as well.
 # So, always() overrides this dependency, helping to execute the following job even when 'tf_apply_secrets' job is skipped.
- 
+
   deploy:
-    needs: [ create_runner, tf_apply_secrets ]
+    needs: [ initChecks, create_runner, tf_apply_secrets ]
     secrets: inherit
     if: ${{ always() && (inputs.run_k8s_workflow && ((!inputs.run_tf_apply_secrets_workflow && needs.tf_apply_secrets.result == 'skipped') || (inputs.run_tf_apply_secrets_workflow && needs.tf_apply_secrets.result == 'success'))) }}
-    uses: ./.github/workflows/deploy-sub.yaml
+    uses: pagopa/interop-infra-commons/.github/workflows/common-k8s-deploy.yaml@e2d6e21c4280fef565526320856e5bbbadd63bbc # v1.25.0
     with:
       environment: ${{ inputs.environment }}
-      timeout_seconds: ${{ vars.ROLLOUT_TIMEOUT_SECONDS || 300 }}
-      force_restart: ${{ inputs.force_restart }}
-      apply_mv: ${{ inputs.apply_mv }}
+      infra_commons_tag: ${{ needs.initChecks.outputs.infra_commons_tag_computed }}
 
   delete_runner:
     name: Delete Self-Hosted Runner
@@ -171,7 +203,7 @@ jobs:
     environment: ${{ inputs.environment }}
     strategy:
       matrix:
-        index: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]
+        index: [1,2,3,4,5,6,7,8,9,10]
       fail-fast: false
     steps:
       - name: Stop Github Runner
