edit kubectl copy command, edit check on created file

diff --git a/.github/workflows/k8s-apply-sub.yaml b/.github/workflows/k8s-apply-sub.yaml
--- a/.github/workflows/k8s-apply-sub.yaml
+++ b/.github/workflows/k8s-apply-sub.yaml
@@ -282,22 +282,16 @@ jobs:
           
           echo "Pod $POD is running"
           echo "Copying ./views folder to Pod..."
-          kubectl cp ./views "$POD":/flyway/sql -n ${{ inputs.environment }}
+          kubectl cp ./views "$POD":/flyway/sql/ -n ${{ inputs.environment }}
           if [ $? -ne 0 ]; then
             echo "Failed to copy ./views folder to Pod."
             exit 1
           else
-            echo "Copy completed successfully."
             kubectl exec -n ${{ inputs.environment }} "$POD" -- touch /tmp/copy_completed.txt
-          fi
-
-      - name: Check copy completion #Necessary? The preceding step checks for the kubectl cp command status code (line 287): if it is different from 0 it exits with an error
-        run: |
-          set -euo pipefail
-
-          if [ -f /tmp/copy_completed.txt ]; then
-            echo "Copy completed successfully."
-          else
-            echo "Copy failed."
-            exit 1
+            if [ $? -ne 0 ]; then
+              echo "Failed to create /tmp/copy_completed.txt file."
+              exit 1
+            else
+              echo "Copy completed successfully."
+            fi
           fi
