replace cmd with function, check kubectl cp command status code

diff --git a/.github/workflows/k8s-apply-sub.yaml b/.github/workflows/k8s-apply-sub.yaml
--- a/.github/workflows/k8s-apply-sub.yaml
+++ b/.github/workflows/k8s-apply-sub.yaml
@@ -267,13 +267,18 @@ jobs:
           echo "Waiting for the Pod to be running..."
 
           timeout 120 bash -c '
-            check_status_cmd='\''
-              POD=$(kubectl get pods -n ${{ inputs.environment }} -l job-name=interop-be-apply-mv-manual -o jsonpath="{.items[0].metadata.name}" 2>/dev/null) &&
-              STATUS=$(kubectl get pod "$POD" -n ${{ inputs.environment }} -o jsonpath="{.status.phase}" 2>/dev/null) &&
-              [ "$STATUS" = "Running" ]
-            '\''
 
-            while ! eval "$check_status_cmd"; do
+            get_pod_status() {
+              POD=$(kubectl get pods -n ${{ inputs.environment }} -l job-name=interop-be-apply-mv-manual -o jsonpath="{.items[0].metadata.name}" 2>/dev/null)
+              STATUS=$(kubectl get pod "$POD" -n ${{ inputs.environment }} -o jsonpath="{.status.phase}" 2>/dev/null)
+              if [ "$STATUS" = "Running" ]; then
+                return 0
+              else
+                return 1
+              fi
+            }
+
+            while ! $get_pod_status; do
               echo "Pod is not running yet. Waiting for the Pod to be running..."
               sleep 10
             done
@@ -281,7 +286,12 @@ jobs:
             echo "Pod $POD is running"
             echo "Copying ./views folder to Pod..."
             kubectl cp ./views "$POD":/flyway/sql -n ${{ inputs.environment }}
-            echo "Copy completed."
+            if [ $? -ne 0 ]; then
+              echo "Failed to copy ./views folder to Pod."
+              exit 1
+            else
+              echo "Copy completed successfully."
+            fi
           ' || {
             echo "Timeout reached while waiting for the Pod to be running."
             exit 1
